# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
import sys
from pathlib import Path

sys.path.insert(0, str(Path('..', 'src').resolve()))

project = 'saigon'
copyright = '2025, Anthony Bastidian'
author = 'Anthony Bastidian'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx_rtd_theme',
    'sphinx_autodoc_typehints'
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# autodoc_default_options = {
#     'members': 'saigon'
# }


def skip_pydantic_internals(app, what, name, obj, skip, options):
    # List names generated by Pydantic that cause duplicates
    pydantic_internals = ["model_config", "model_fields", "model_computed_fields"]
    if name in pydantic_internals:
        return True
    return skip


def setup(app):
    app.connect('autodoc-skip-member', skip_pydantic_internals)


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_type_aliases = None
napoleon_attr_annotations = True
